# Generated by Django 5.0.6 on 2024-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='is_clientadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
