# Generated by Django 5.0.6 on 2024-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_superadmin_is_clientadmin_superadmin_is_superadmin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='superadmin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='username',
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
